surface.CreateFont("gScooters.Font.Main", {font = "Open Sans", size = 65, weight = 2000, shadow = false})
surface.CreateFont("gScooters.Font.LargeText", {font = "Open Sans", size = 57, weight = 500, shadow = true})
surface.CreateFont("gScooters.Font.Text", {font = "Open Sans", size = 30, weight = 500, shadow = false})
surface.CreateFont("gScooters.Font.Bold", {font = "Open Sans", size = 40, weight = 2000, shadow = false})
surface.CreateFont("gScooters.Font.BoldItalic", {font = "Open Sans", size = 40, weight = 2000, shadow = false, italic = true})
surface.CreateFont("gScooters.Font.Logo", {font = "Montserrat Thin", size = 30, weight = 500, shadow = false})
surface.CreateFont("gScooters.Font.MediumText", {font = "Open Sans", size = 20, weight = 600, shadow = false})
surface.CreateFont("gScooters.Font.MediumTextItalic", {font = "Open Sans", size = 20, weight = 600, shadow = false, italic = true})
surface.CreateFont("gScooters.Font.Small", {font = "Open Sans", size = 16, weight = 0, antialias = true})
surface.CreateFont("gScooters.Font.SmallBoldItalic", {font = "Open Sans", size = 14, weight = 2000, antialias = true})
surface.CreateFont("gScooters.Font.Speedo", {font = "Digital-7", size = 140, antialias = true})
