if (SERVER) then
    AddCSLuaFile('client/graffiti-ui-settings.lua')
elseif (CLIENT) then
    include('client/graffiti-ui-settings.lua')

    surface.CreateFont("Graffiti:Fonts:Montserrat25", {
        font = "Montserrat",
        size = 25
    })

    surface.CreateFont("Graffiti:Fonts:Montserrat25Bold", {
        font = "Montserrat Medium",
        size = 25
    })
end

function SWEP:GraffitiUI()
    if (CLIENT) then

        net.Start('GraffitiUIOpenCnanger')
            net.WriteString('1')
        net.SendToServer()

        local Frame = vgui.Create('DFrame')
            Frame:SetSize(285, 360)
            Frame:Center()
            Frame:SetTitle('')
            Frame:SetVisible(true)
            Frame:SetDraggable(false)
            Frame:ShowCloseButton(false)
            Frame:SetPaintShadow(true)
            Frame:MakePopup()

            Frame.Paint = function(self, w, h)
                draw.RoundedBox(8, 0, 0, w, h, Color(32, 30, 31))
                draw.RoundedBox(0, 0, 10, w, 24, Color(46, 43, 45))
                draw.RoundedBox(8, 0, 0, w, 34, Color(46, 43, 45))

                draw.SimpleText("Graffiti", "Graffiti:Fonts:Montserrat25", 10, 15, color_white, TEXT_ALIGN_LEFT, TEXT_ALIGN_CENTER)
                draw.SimpleText("Colors", "Graffiti:Fonts:Montserrat25Bold", 25, 50, color_white, TEXT_ALIGN_LEFT, TEXT_ALIGN_CENTER)
                draw.SimpleText("Sizes", "Graffiti:Fonts:Montserrat25Bold", 25, 240, color_white, TEXT_ALIGN_LEFT, TEXT_ALIGN_CENTER)
            end
            local CloseBTN = vgui.Create('DButton', Frame)

            -- Définition de la fonction RX
            local function RX(pixels)
                return pixels * (ScrW() / 1920) -- Remplacez 1920 par la largeur de référence de votre UI
            end
            
            -- Définition de la fonction RY si nécessaire (pour les valeurs en hauteur)
            local function RY(pixels)
                return pixels * (ScrH() / 1080) -- Remplacez 1080 par la hauteur de référence de votre UI
            end
            
            -- Utilisation de RX dans votre code
            CloseBTN:SetSize(RX(30), RY(30))
            CloseBTN:SetText("")
            CloseBTN:SetPos(CloseBTN:GetParent():GetWide() - CloseBTN:GetWide(), 0)
            
            function CloseBTN:DoClick()
                net.Start('GraffitiUIOpenCnanger')
                    net.WriteString('0')
                net.SendToServer()
                CloseBTN:GetParent():Remove()
            end
            
            function CloseBTN:Paint(w, h)
                draw.SimpleText("✕", "Graffiti:Fonts:Montserrat25", w / 2, h / 2, color_white, TEXT_ALIGN_CENTER, TEXT_ALIGN_CENTER)
            end

----------------------

            local DColor = vgui.Create('DLabel', Frame)
                DColor:SetPos(15, 397)
                DColor:SetSize(180, 25)
                DColor:SetColor(Color(255, 255, 255, 0))
                if (LocalPlayer():GetNWBool('GraffitiBrush') == true) then
                    DColor:SetText('Brush: ')
                else
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                end
            local DSize = vgui.Create('DLabel', Frame)
                DSize:SetPos(95, 400)
                DSize:SetColor(Color(255, 255, 255, 0))
                if (LocalPlayer():GetNWBool('GraffitiBrush') == true) then
                    DSize:SetText('')
                else
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                end
            local DBrush = vgui.Create('DLabel', Frame)
                DBrush:SetPos(50, 400)
                DBrush:SetColor(Color(255, 255, 255, 0))
                if (LocalPlayer():GetNWBool('GraffitiBrush') == true) then
                    DBrush:SetText(LocalPlayer():GetNWString('GraffitiColor'))
                else
                    DBrush:SetText('')
                end

----------------------
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(25, 70)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(0, 68, 46, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Fir')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Fir')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(65, 70)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(23, 171, 137, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Emerald')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Emerald')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(105, 70)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(77, 170, 71, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Mint')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Mint')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(145, 70)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(35, 100, 176, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Ocean')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Ocean')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(185, 70)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(83, 148, 204, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Sky')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Sky')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(225, 70)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(188, 204, 233, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Linen')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Linen')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(25, 110)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(255, 207, 58, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Corn')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Corn')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(65, 110)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(247, 215, 141, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Gold')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Gold')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(105, 110)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(252, 223, 45, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Lemon')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Lemon')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(145, 110)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(217, 224, 31, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Barberry')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Barberry')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(185, 110)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(255, 237, 179, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Biscuit')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Biscuit')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(225, 110)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(218, 181, 154, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Skin')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Skin')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(25, 150)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(222, 90, 55, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Coral')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Coral')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(65, 150)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(241, 89, 83, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Assol')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Assol')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(105, 150)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(246, 146, 35, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Orange')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Orange')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(145, 150)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(203, 157, 200, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Lavender')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Lavender')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(185, 150)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(145, 121, 183, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Lilac')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Lilac')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(225, 150)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(144, 59, 126, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Plum')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Plum')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(25, 190)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(0, 0, 0, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Black')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Black')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(65, 190)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(90, 90, 92, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Graphite')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Graphite')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(105, 190)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(103, 104, 106, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Shadow')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Shadow')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(145, 190)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(147, 149, 157, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Asphalt')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Asphalt')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(185, 190)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(241, 241, 242, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Silver')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Silver')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(225, 190)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(255, 255, 255, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'White')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('White')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
----------------------
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(25, 260)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                    draw.RoundedBox(5, 0, 0, w, h, Color(46, 43, 45))
                    draw.RoundedBox(360, 10, 10, w-20, h-20, Color(216, 36, 36))
                end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiSize', 'Small')
                    net.Start('GraffitiSizeChanger')
                        net.WriteString('Small')
                    net.SendToServer()
                    if (LocalPlayer():GetNWBool('GraffitiBrush') == true) then
                        DSize:SetText('')
                    else
                        DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    end
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(65, 260)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                    draw.RoundedBox(5, 0, 0, w, h, Color(46, 43, 45))
                    draw.RoundedBox(360, 7, 7, w-14, h-14, Color(216, 36, 36))
                end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiSize', 'Normal')
                    net.Start('GraffitiSizeChanger')
                        net.WriteString('Normal')
                    net.SendToServer()
                    if (LocalPlayer():GetNWBool('GraffitiBrush') == true) then
                        DSize:SetText('')
                    else
                        DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    end
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(105, 260)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                    draw.RoundedBox(5, 0, 0, w, h, Color(46, 43, 45))
                    draw.RoundedBox(360, 4, 4, w-8, h-8, Color(216, 36, 36))
                end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiSize', 'Large')
                    net.Start('GraffitiSizeChanger')
                        net.WriteString('Large')
                    net.SendToServer()
                    if (LocalPlayer():GetNWBool('GraffitiBrush') == true) then
                        DSize:SetText('')
                    else
                        DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    end
                end
----------------------
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(25, 305)
                DermaButton:SetSize(235, 35)
                DermaButton.Paint = function(self, w, h)
                    draw.RoundedBox(5, 0, 0, w, h, Color(46, 43, 45))

                    if self:IsHovered() then 
                        draw.RoundedBox(4, 0, h - RY(4), Lerp((CurTime() - self.FF4TimeBeforeHover)*4, 0, w ), RY(4), Color(86, 184, 209))
                    else 
                        self.FF4TimeBeforeHover = CurTime()
                    end

                    draw.SimpleText("Confirm", "Graffiti:Fonts:Montserrat25Bold", w / 2, h / 2, color_white, TEXT_ALIGN_CENTER, TEXT_ALIGN_CENTER)
                end
                DermaButton.DoClick = function()
                    local ply = LocalPlayer()
                    file.Write('graffiti-swep/graffiti-settings.txt', ply:GetNWString('GraffitiColor') .. '\n' .. ply:GetNWString('GraffitiSize') .. '\n' .. tostring(ply:GetNWBool('GraffitiBrush')) .. '\n' .. ply:GetNWInt('GraffitiSpraying') .. '\n' .. ply:GetNWInt('GraffitiSlider'))

                    net.Start('GraffitiUIOpenCnanger')
                        net.WriteString('0')
                    net.SendToServer()
                    CloseBTN:GetParent():Remove()
                end
    end
end