bKeypads.Cracker:SetConfig({ -- Don't touch this line

--################################################################################################################--
--[[##############################################################################################################--
      
      
       ██████╗ ██╗██╗     ██╗  ██╗   ██╗███████╗    ██╗  ██╗███████╗██╗   ██╗██████╗  █████╗ ██████╗ ███████╗
       ██╔══██╗██║██║     ██║  ╚██╗ ██╔╝██╔════╝    ██║ ██╔╝██╔════╝╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗██╔════╝
       ██████╔╝██║██║     ██║   ╚████╔╝ ███████╗    █████╔╝ █████╗   ╚████╔╝ ██████╔╝███████║██║  ██║███████╗
       ██╔══██╗██║██║     ██║    ╚██╔╝  ╚════██║    ██╔═██╗ ██╔══╝    ╚██╔╝  ██╔═══╝ ██╔══██║██║  ██║╚════██║
       ██████╔╝██║███████╗███████╗██║   ███████║    ██║  ██╗███████╗   ██║   ██║     ██║  ██║██████╔╝███████║
       ╚═════╝ ╚═╝╚══════╝╚══════╝╚═╝   ╚══════╝    ╚═╝  ╚═╝╚══════╝   ╚═╝   ╚═╝     ╚═╝  ╚═╝╚═════╝ ╚══════╝
      

    https://www.gmodstore.com/market/view/billys-keypads
    
    Thank you for purchasing my script and supporting my work :D I hope this will enrich your server.
	Make sure you've followed the installation instructions and activated your license if you haven't already.

	Using a leak? That's okay -- sometimes it's hard to justify splashing out on a new server, for example.
	But please be safe - the VAST majority of leaks contain backdoors and malicious code that can destroy
	your server and attract malicious players.

	If your server is successful, don't forget to support the creators who provided you with their hard work.

--################################################################################################################--
--################################################################################################################--

	This Lua file allows you to configure Billy's Deployable Keypad Crackers.

	PLEASE DO NOT EDIT THIS FILE IN NOTEPAD - IT'S LIKE TRYING TO DO SURGERY WITH A KITCHEN KNIFE.
	Use one of these:
	https://www.sublimetext.com/
	https://notepad-plus-plus.org/downloads/
	https://code.visualstudio.com/

	Unfortunately I cannot provide support regarding configuring the addon as I would just get flooded and wouldn't
	have time to help people with bugs or errors so please reach out to friends or the Internet if you need help.

	It follows the same syntax as actual Lua code so if you make a typo you are likely to break it. Be careful.

	Don't change anything in this file except for the settings themselves unless you know what you are doing.

	This config file uses Simplerr (the same thing DarkRP uses) to help you understand any errors.
	https://fptje.github.io/glualint-web/ can also help you debug your config file.

	Good luck, have fun :D

]]--##############################################################################################################--
--##[[                                                  DarkRP                                                ]]##--

-- Want to make a job spawn with a keypad cracker?
-- Give them the bkeypads_cracker weapon :)

F4Cracker = {
	-- Should the keypad cracker be added to the DarkRP F4 menu as a purchaseable weapon?
	EnableSingle = false,

	-- Should the keypad cracker be added to the DarkRP F4 menu as a purchaseable shipment?
	EnableShipment = false,

	Single = {
		-- The name of the F4 menu weapon
		-- If changing this doesn't work, your F4 menu isn't very well made
		label = "Keypad Cracker",

		amount = 1,
		price = 500,

		sortOrder = 0,
		category = "Other",

		customCheck = function(ply)
			return table.HasValue(ply:getJobTable().weapons, "bkeypads_cracker") -- This means only people whose job spawns with a keypad cracker can buy it
		end,
	},

Shipment = {
		-- The name of the F4 menu shipment
		-- If changing this doesn't work, your F4 menu isn't very well made
	label = "Keypad Cracker",

		amount = 10,
		allowed = { TEAM_GUN },
	price = 5000,

	sortOrder = 0,
	category = "Other",
	},
},

--################################################################################################################--
--##[[                                                  CONFIG                                                ]]##--

-- While cracking, should the keypad cracker be deployed on the keypad, or should it be held in the players hands?
Deployed = true,

-- How long does it take to crack a keypad in seconds?
-- The cracking time is chosen randomly in between the two numbers, e.g. between 20 and 30 seconds.
-- The first number is the lower range, and the second number is the higher range.
CrackTime = { 10, 15 },

-- Here you can define special crack times
-- If a player is eligible for multiple special crack times, the one with the shortest duration will be selected.
SpecialCrackTimes = {
	-- Usergroups
	{ "superadmin", "vip", "viprehber", "moderator", "moderator+", "admin", "admin+", "basadmin", {5, 10} },
	{ "banned", {999999, 999999} },

	-- Teams/Jobs
	{TEAM_HIRSIZ, {5, 10} },
	{TEAM_PROFHIRSIZ, {1, 5} },
	--{ TEAM_STAFF, {1, 1} },

	--[[
	Custom check functions for advanced users

	{
		-- This special crack time will only apply to DarkRP police
		function(ply, keypad)
			if DarkRP and ply.isCP and ply:isCP() then
				return true
			end
		end,

		{30, 60}
	},

	{
		function(ply, keypad)
			return ply:SteamID() == "STEAM_0:1:40314158"
		end,
		
		-- You can also specify your own custom function for the crack time
		function(ply, keypad)
			return math.random(1, 5)
		end,
	},

	--]]
},

-- Add sunglasses to keypad cracker faces for players with special crack times?
SpecialSunglasses = false,

-- (DarkRP only) How much money to give a police officer if they stunstick a keypad cracker?
SeizeReward = 500,

-- (DarkRP only) Should the stunstick destroy keypad crackers or simply drop them off keypads?
StunstickDestroys = false,

-- Distance keypad cracker can be deployed from
CrackDistance = 2500,

-- Should a player's DEPLOYED (actively cracking) keypad crackers be destroyed when they disconnect?
DestroyDeployedCrackersOnDisconnect = true,

-- Should a player's DROPPED (on the ground) keypad crackers be destroyed when they disconnect?
DestroyDroppedCrackersOnDisconnect = true,

-- Should a player's DEPLOYED (actively cracking) keypad crackers be destroyed if they die?
DestroyDeployedCrackersOnDeath = false,

-- Should a player's DROPPED (on the ground) keypad crackers be destroyed if they die?
DestroyDroppedCrackersOnDeath = true,

-- Should a player's DEPLOYED (actively cracking) keypad crackers be destroyed if they switch teams?
DestroyDeployedCrackersOnSwitch = true,

-- Should a player's DROPPED (on the ground) keypad crackers be destroyed if they switch teams?
DestroyDroppedCrackersOnSwitch = true,

-- Should DEPLOYED (actively cracking) keypad crackers be destroyed when they finish cracking?
-- This makes them one-time use items.
DestroyCrackersWhenFinished = false,

-- Should a player's DEPLOYED (actively cracking) keypad crackers be REPLACED if they crack a different keypad?
ReplaceOldDeployedCrackers = true,

-- Should a player's DROPPED (on the ground) keypad crackers be REPLACED if they crack a different keypad?
ReplaceOldDroppedCrackers = true,

-- If a player's keypad cracker gets destroyed, magically give them a new one?
ReplaceDestroyedCrackers = true,

-- In seconds, how long should it take for a DROPPED (on the ground) keypad cracker to destroy itself?
-- Set to 0 to disable
DroppedKeypadCrackerTimeout = 600,

-- Allow players to pick up DROPPED (on the ground) keypad crackers even if they didn't deploy them?
-- NOTE: This can be controlled through OpenPermissions (allowing you to specify teams that can pick them up)
AnyoneCanPickup = false,

-- Allow players to stop DEPLOYED (actively cracking) keypad crackers by pressing E even if they didn't deploy them?
-- Does nothing if keypad cracker damage is enabled.
-- NOTE: This can be controlled through OpenPermissions (allowing you to specify teams that can pick them up)
AnyoneCanStopCracker = true,

-- Allow players who spawned with the keypad cracker to pick up DROPPED (on the ground) keypad crackers even if they didn't deploy them?
LoadoutCanPickup = true,

-- Should DROPPED (on the ground) keypad crackers be visible through walls to the player who deployed it?
SeeDroppedCrackerThroughWalls = true,

Damage = {
	-- Can keypad crackers take damage?
	Enable = true,

	-- Should keypad crackers that take damage be destroyed by it?
	-- If not, they will simply drop off the keypad
	Destroy = true,
	
	-- Can DROPPED keypad crackers be destroyed?
	-- Does nothing if Destroy is false
	CanDestroyDropped = true,

	-- How much damage is required for a deployed cracker to drop off a keypad?
	-- Set to 0 for instant drop
	Health = 500,

	-- Show a health bar on DEPLOYED (actively cracking) keypad crackers?
	HealthBar = true,

	-- Should only certain damage types damage the keypad cracker?
	-- https://wiki.facepunch.com/gmod/Enums/DMG
	DamageTypeWhitelist = {
		DMG_BULLET,
		DMG_SLASH,
		DMG_CLUB,
		DMG_BUCKSHOT,
		DMG_SNIPER,
		DMG_GENERIC,
	},
	
	-- Should certain damage types be blocked from damaging the keypad cracker?
	-- https://wiki.facepunch.com/gmod/Enums/DMG
	DamageTypeBlacklist = {
		DMG_VEHICLE,
		DMG_POISON,
		DMG_PHYSGUN,
	},

	-- Allow bullets to damage keypads through walls?
	DamageThroughWalls = false,

	-- Should damage apply force to dropped keypad crackers?
	-- Players will be able to shoot dropped keypad crackers around
	DamageForce = true,
},

Beeps = {
	-- Emit the classic keypad cracking beep noises?
	Enable = true,

	-- How often should beeps be played?
	BeepInterval = 1,

	-- The distance/volume the beeps can be heard from.
	-- Measured in dB, https://wiki.facepunch.com/gmod/Enums/SNDLVL
	-- Don't actually use SNDLVL_* here, use the number they represent
	BeepVolume = 100,
},

-- Should there be a random chance that a keypad crack could fail entirely?
-- 0 = never fail
-- 1 = always fail
FailChance = 0,

-- Should the keypad cracker trigger "Access Denied" on the keypad if it fails?
AccessDeniedOnFail = true,

-- Should the keypad cracker trigger "Access Denied" on the keypad if cracking is somehow aborted?
AccessDeniedOnAbort = false,

-- The phrases shown on the keypad cracker's screen when it's being deployed
-- Only alphanumeric latin characters are supported (A-Z a-z 0-9)
CrackerPhrases = {
    "OHH EVET",
    "NIHAYET",
    "HADI GIDELIM",
    "HAHAHAHA",
    "VAKIT GELDI",
    "LOL KOLAY",
    "BENI KORU",
    "UNUTMA",
    "SENI SEVIYORUM",
    "IYI SANSLAR",
    "BUNU BAŞARABILIRSIN",
}



















--################################################################################################################--
--################################################################################################################--
}) -- Don't touch this line