--[[
This code was generated by LAUX, a Lua transpiler
LAUX is a fork of LAU with additional changes.

More info & source code can be found at: https://gitlab.com/sleeppyy/laux
]]

local LANG = {
["ConCommand.Drop"]                          = ":item: atıldı",
["ConCommand.DropAll"]                       = ":amount:x adet :item: atıldı",
["ConCommand.Destroy"]                       = ":amount:x adet :item: yok edildi",
["ConCommand.Destroy.Popup.Title"]           = ":item: yok et",
["ConCommand.Destroy.Popup.Desc"]            = ":item: yok etmek istediğine emin misin?",
["ConCommand.Destroy.Popup.Yes"]             = "Evet",
["ConCommand.Destroy.Popup.No"]              = "Hayır",

["ChatCommand.Holster.Unable"]               = "Sınırlı envanter alanın nedeniyle bu silahı kılıfa takamazsın",
["ChatCommand.Blacklisted"]                  = "Bu öğe kara listede",
["ChatCommand.AccessRestricted"]             = "Envanterine erişimin şu anda kısıtlı",

["Bank.Title"]                               = "Envanter - Banka",
["XeninInventory.Title"]                     = "Envanter",

["XeninInventory.Tabs.XeninInventory"]       = "ENVANTER",

["XeninInventory.Popup.Equip"]               = "KUŞAN",
["XeninInventory.Popup.Drop"]                = "AT",
["XeninInventory.Popup.Drop All"]            = "HEPSİNİ AT",
["XeninInventory.Popup.Destroy"]             = "YOK ET",
["XeninInventory.Popup.Use"]                 = "KULLAN",
["XeninInventory.Popup.Drop Amount"]         = "MİKTAR AT",

["XeninInventory.Popup.DropAmount.Error.Invalid"]  = "Geçersiz sayı?",
["XeninInventory.Popup.DropAmount.Error.TooLow"]   = "Sayının değeri çok düşük",
["XeninInventory.Popup.DropAmount.Error.TooHigh"]  = "Bundan fazla atamazsın çünkü o kadarın yok!",

["XeninInventory.Actions.Equip"]             = "KUŞAN",
["XeninInventory.Actions.Drop"]              = "AT",
["XeninInventory.Actions.Drop All"]          = "HEPSİNİ AT",
["XeninInventory.Actions.Destroy"]           = "YOK ET",
["XeninInventory.Actions.Use"]               = "KULLAN",
["XeninInventory.Actions.Drop Amount"]       = "MİKTAR AT",

["XeninInventory.Field.Amount"]              = "x:amount: adet",
["XeninInventory.Field.MaxAmount"]           = "maks x:amount: adet",

["XeninInventory.XeninInventory.Search"]     = "Bir öğe ara",

["XeninInventory.XeninInventory.Unsorted"]   = "Sıralanmamış",
["XeninInventory.XeninInventory.Alphabetically"] = "Alfabetik",
["XeninInventory.XeninInventory.WorstToBest"]    = "En kötünden en iyiye",
["XeninInventory.XeninInventory.BestToWorst"]    = "En iyiden en kötüye",

["XeninInventory.Shipment.Desc"]             = ":amount: silah kaldı",

["XeninInventory.Pickup.Markup"]             = ":font::color:Bas :/color::rarityColor::modifierKey: + :key::/color: ile :name: öğesini envanterine eklemek için:/color::/font:",
["XeninInventory.Pickup"]                    = "Bas :modifierKey: + :key: ile :name: öğesini envanterine eklemek için",
["XeninInventory.Money"]                     = ":money:",

["Admin.Title"]                              = "Envanter Yöneticisi",
["Admin.Tabs.Management"]                    = "YÖNETİM",
["Admin.NotAdmin"]                           = "Bunu açmak için envanter yöneticisi olmalısın!",

["Admin.Management.Loading"]                 = "Yükleniyor",
["Admin.Management.Search"]                  = "İsim/SteamID(64) ile ara",
["Admin.Management.Searching"]               = "Aranıyor",
["Admin.Management.Online"]                  = "Çevrimiçi",
["Admin.Management.Offline"]                 = "Çevrimdışı",
["Admin.Management.OpenInventory"]           = "Envanteri Aç",

["Admin.Player.Title"]                       = "Oyuncu Envanteri",
["Admin.Player.Tabs.XeninInventory"]         = "ENVANTER",
["Admin.Player.Tabs.Bank"]                   = "BANKA",
["Admin.Player.Items"]                       = ":items: öğe",
["Admin.Player.Clear.XeninInventory"]        = "Envanteri Temizle",
["Admin.Player.Clear.Bank"]                  = "Bankayı Temizle",
["Admin.Player.Clear.Popup.Text"]            = "Bu oyuncunun :type: öğelerini temizlemek istediğine emin misin? Bu işlem geri alınamaz!",
["Admin.Player.Clear.Popup.Yes"]             = "Evet, temizle",
["Admin.Player.Clear.Popup.No"]              = "Hayır",

["Admin.Clear.Slot"]                         = ":type: slot numarası :id:, bir yönetici tarafından temizlendi",
["Admin.Clear"]                              = ":type: öğelerin, bir yönetici tarafından temizlendi",

}

XeninInventory:CreateLanguage("English", LANG)
