ADRLang = ADRLang or {}

/*---------------------------------------------------------------------------
English - en
---------------------------------------------------------------------------*/
ADRLang.en = ADRLang.en or {}
ADRLang.en["DAY"] = "DAY"
ADRLang.en["TIME"] = "TIME"
ADRLang.en["EXPIRATION_DATE"] = "EXPIRATION DATE"
ADRLang.en["UNTIL_THE_END"] = "UNTIL THE END"
ADRLang.en["CURRENT_TASKS"] = "CURRENT TASKS"
ADRLang.en["Completed"] = "Completed"
ADRLang.en["PREMIUM"] = "PREMIUM"

ADRLang.en["SETTINGS"] = "SETTINGS"
ADRLang.en["Themes"] = "Themes"
ADRLang.en["ThemesHint"] = "List of themes that can be selected for visual design"
ADRLang.en["Season_Name"] = "Season Name"
ADRLang.en["SNameHint"] = "The name of the season to be displayed in the bottom left block. May not be unique"
ADRLang.en["File_Name"] = "File Name"
ADRLang.en["SFileHint"] = "A unique name that is assigned to the season information file. If you write the name of an already existing file, it will overwrite it when you save it. Must be specified in Latin letters without spaces and special characters!"
ADRLang.en["Time"] = "Time"
ADRLang.en["TimeHint"] = "How many days will the season last"
ADRLang.en["Task"] = "Task"
ADRLang.en["TaskHint"] = "Reward for completing tasks. Tasks will be disabled if there is no reward and the «TasksForClaim» setting is disabled in the config"
ADRLang.en["Actions"] = "Actions"
ADRLang.en["ActionsHint"] = "Action list for managing templates and the current season"
ADRLang.en["New"] = "New"
ADRLang.en["Load"] = "Load"
ADRLang.en["Save"] = "Save"
ADRLang.en["Remove"] = "Remove"
ADRLang.en["Start"] = "Start"
ADRLang.en["Stop"] = "Stop"
ADRLang.en["Confirm"] = "Confirm"
ADRLang.en["Cancel"] = "Cancel"
ADRLang.en["Reward"] = "Reward"
ADRLang.en["Module"] = "Module"
ADRLang.en["Name"] = "Name"
ADRLang.en["Reward_name"] = "Reward name"
ADRLang.en["New_File"] = "New File"
ADRLang.en["FileStatus"] = "File: "

ADRLang.en["CreateNew"] = "Create New"
ADRLang.en["StartSeason"] = "Start Season"
ADRLang.en["StopSeason"] = "Stop Season"
ADRLang.en["ActionNew"] = "Do you want to reset everything to its original state?\nYou will lose your current settings if you have not\nsaved them."
ADRLang.en["ActionSave"] = "Do you want to save the preset?\nThis will overwrite the existing file if there is one."
ADRLang.en["ActionRemove"] = "Are you sure you want to delete the preset?\nThis will remove the players progress and you will\nno longer be able to go back to that season."
ADRLang.en["ActionStart"] = "Do you want to start the season with your chosen\nsettings?\nThis will stop the current season and start a new one."
ADRLang.en["ActionStop"] = "Do you really want to stop the current season?\nYou can start it later at any time."

/*---------------------------------------------------------------------------
Russian - ru
---------------------------------------------------------------------------*/
ADRLang.ru = ADRLang.ru or {}
ADRLang.ru["DAY"] = "ДЕНЬ"
ADRLang.ru["TIME"] = "СРОК"
ADRLang.ru["EXPIRATION_DATE"] = "ДАТА ОКОНЧАНИЯ"
ADRLang.ru["UNTIL_THE_END"] = "ДО ОКОНЧАНИЯ"
ADRLang.ru["CURRENT_TASKS"] = "ЗАДАНИЯ"
ADRLang.ru["Completed"] = "Выполнено"
ADRLang.ru["PREMIUM"] = "PREMIUM"

ADRLang.ru["SETTINGS"] = "НАСТРОЙКИ"
ADRLang.ru["Themes"] = "Темы"
ADRLang.ru["ThemesHint"] = "Список тем, которые могут быть выбраны для отображения"
ADRLang.ru["Season_Name"] = "Имя Сезона"
ADRLang.ru["SNameHint"] = "Название сезона, которое будет отображаться в нижнем левом блоке. Может быть не уникальным"
ADRLang.ru["File_Name"] = "Имя Файла"
ADRLang.ru["SFileHint"] = "Уникальное имя, которое присваивается файлу с информацией про сезон. Если вы напишите имя уже существующего файла, то при сохранении оно перезапишет его. Должно быть указано латинскими буквами без пробелов и специальных знаков!"
ADRLang.ru["Time"] = "Время"
ADRLang.ru["TimeHint"] = "Сколько дней будет продолжаться сезон"
ADRLang.ru["Task"] = "Задание"
ADRLang.ru["TaskHint"] = "Награда за выполнение заданий. Задания будут отключены если награда отсутствует и в конфиге отключена настройка «TasksForClaim»"
ADRLang.ru["Actions"] = "Действия"
ADRLang.ru["ActionsHint"] = "Список действий для управления шаблонами и текущим сезоном"
ADRLang.ru["New"] = "Новый"
ADRLang.ru["Load"] = "Загрузить"
ADRLang.ru["Save"] = "Сохранить"
ADRLang.ru["Remove"] = "Удалить"
ADRLang.ru["Start"] = "Начать"
ADRLang.ru["Stop"] = "Остановить"
ADRLang.ru["Confirm"] = "Подтвердить"
ADRLang.ru["Cancel"] = "Отмена"
ADRLang.ru["Reward"] = "Награда"
ADRLang.ru["Module"] = "Модуль"
ADRLang.ru["Name"] = "Имя"
ADRLang.ru["Reward_name"] = "Имя награды"
ADRLang.ru["New_File"] = "Новый Файл"
ADRLang.ru["FileStatus"] = "Файл: "

ADRLang.ru["CreateNew"] = "Создать Новый"
ADRLang.ru["StartSeason"] = "Начать Сезон"
ADRLang.ru["StopSeason"] = "Остановить Сезон"
ADRLang.ru["ActionNew"] = "Хотите вернуть все в исходное состояние?\nЕсли вы не сохранили текущие настройки, они\nбудут потеряны."
ADRLang.ru["ActionSave"] = "Хотите сохранить предустановку?\nЭто перезапишет существующий файл, если он есть."
ADRLang.ru["ActionRemove"] = "Вы уверены, что хотите удалить предустановку?\nЭто удалит прогресс игроков, и вы больше не\nсможете вернуться к этому сезону."
ADRLang.ru["ActionStart"] = "Хотите начать сезон с выбранными настройками?\nЭто остановит текущий сезон и начнет новый."
ADRLang.ru["ActionStop"] = "Вы действительно хотите остановить текущий сезон?\nВы можете начать его позже в любое время."

/*---------------------------------------------------------------------------
Ukrainian - uk
---------------------------------------------------------------------------*/
ADRLang.uk = ADRLang.uk or {}
ADRLang.uk["DAY"] = "ДЕНЬ"
ADRLang.uk["TIME"] = "ТЕРМІН"
ADRLang.uk["EXPIRATION_DATE"] = "ДАТА ЗАВЕРШЕННЯ"
ADRLang.uk["UNTIL_THE_END"] = "ДО ЗАВЕРШЕННЯ"
ADRLang.uk["CURRENT_TASKS"] = "ЗАВДАННЯ"
ADRLang.uk["Completed"] = "Виконано"
ADRLang.uk["PREMIUM"] = "ПРЕМІУМ"

ADRLang.uk["SETTINGS"] = "НАЛАШТУВАННЯ"
ADRLang.uk["Themes"] = "Теми"
ADRLang.uk["ThemesHint"] = "Список тем, які можуть бути обрані для відображення"
ADRLang.uk["Season_Name"] = "Ім'я Сезону"
ADRLang.uk["SNameHint"] = "Назва сезону, яка відображатиметься в нижньому лівому блоці. Може бути не унікальною"
ADRLang.uk["File_Name"] = "Ім'я Файлу"
ADRLang.uk["SFileHint"] = "Унікальне ім'я, яке присвоюється файлу з інформацією про сезон. Якщо ви напишете ім'я вже наявного файлу, то під час збереження воно перезапише його. Має бути вказано латинськими літерами без пробілів і спеціальних знаків!"
ADRLang.uk["Time"] = "Час"
ADRLang.uk["TimeHint"] = "Скільки днів триватиме сезон"
ADRLang.uk["Task"] = "Завдання"
ADRLang.uk["TaskHint"] = "Нагорода за виконання завдань. Завдання будуть відключені, якщо нагорода відсутня і в конфігурації відключено налаштування «TasksForClaim»"
ADRLang.uk["Actions"] = "Дії"
ADRLang.uk["ActionsHint"] = "Список дій для управління шаблонами та поточним сезоном"
ADRLang.uk["New"] = "Новий"
ADRLang.uk["Load"] = "Завантажити"
ADRLang.uk["Save"] = "Зберегти"
ADRLang.uk["Remove"] = "Видалити"
ADRLang.uk["Start"] = "Почати"
ADRLang.uk["Stop"] = "Зупинити"
ADRLang.uk["Confirm"] = "Підтвердити"
ADRLang.uk["Cancel"] = "Скасувати"
ADRLang.uk["Reward"] = "Нагорода"
ADRLang.uk["Module"] = "Модуль"
ADRLang.uk["Name"] = "Ім'я"
ADRLang.uk["Reward_name"] = "Назва нагороди"
ADRLang.uk["New_File"] = "Новий Файл"
ADRLang.uk["FileStatus"] = "Файл: "

ADRLang.uk["CreateNew"] = "Створити Новий"
ADRLang.uk["StartSeason"] = "Розпочати Сезон"
ADRLang.uk["StopSeason"] = "Зупинити Сезон"
ADRLang.uk["ActionNew"] = "Хочете повернути все в початковий стан?\nЯкщо ви не зберегли поточні налаштування,\nїх буде втрачено."
ADRLang.uk["ActionSave"] = "Хочете зберегти поточні налаштування?\nЦе перезапише наявний файл, якщо він є."
ADRLang.uk["ActionRemove"] = "Ви впевнені, що хочете видалити поточні\nналаштування?\nЦе видалить прогрес гравців, і ви більше не зможете\nповернутися до цього сезону."
ADRLang.uk["ActionStart"] = "Хочете почати сезон з обраними налаштуваннями?\nЦе зупинить поточний сезон і почне новий."
ADRLang.uk["ActionStop"] = "Ви дійсно хочете зупинити поточний сезон?\nВи можете розпочати його пізніше в будь-який час."
/*---------------------------------------------------------------------------
French - fr
---------------------------------------------------------------------------*/
ADRLang.fr = ADRLang.fr or {}
ADRLang.fr["DAY"] = "JOUR"
ADRLang.fr["TIME"] = "TEMPS"
ADRLang.fr["EXPIRATION_DATE"] = "DATE D'EXPIRATION"
ADRLang.fr["UNTIL_THE_END"] = "JUSQU'À LA FIN"
ADRLang.fr["CURRENT_TASKS"] = "TÂCHES ACTUELLES"
ADRLang.fr["Completed"] = "Terminé"
ADRLang.fr["PREMIUM"] = "PREMIUM"

ADRLang.fr["SETTINGS"] = "PARAMÈTRES"
ADRLang.fr["Themes"] = "Thèmes"
ADRLang.fr["ThemesHint"] = "Liste des thèmes pouvant être sélectionnés pour la conception visuelle"
ADRLang.fr["Season_Name"] = "Nom de la saison"
ADRLang.fr["SNameHint"] = "Le nom de la saison à afficher dans le bloc inférieur gauche. Peut ne pas être unique"
ADRLang.fr["File_Name"] = "Nom du fichier"
ADRLang.fr["SFileHint"] = "Nom unique attribué au fichier d'informations sur la saison. Si vous écrivez le nom d'un fichier déjà existant, celui-ci sera écrasé lorsque vous l'enregistrerez. Doit être spécifié en lettres latines, sans espaces ni caractères spéciaux !"
ADRLang.fr["Time"] = "L'heure"
ADRLang.fr["TimeHint"] = "Combien de jours durera la saison"
ADRLang.fr["Task"] = "Tâche"
ADRLang.fr["TaskHint"] = "Récompense pour l'accomplissement des tâches. Les tâches seront désactivées s'il n'y a pas de récompense et si le paramètre «TasksForClaim» est désactivé dans la configuration."
ADRLang.fr["Actions"] = "Actions"
ADRLang.fr["ActionsHint"] = "Liste d'actions pour la gestion des modèles et de la saison en cours"
ADRLang.fr["New"] = "Nouveau"
ADRLang.fr["Load"] = "Chargement"
ADRLang.fr["Save"] = "Enregistrer"
ADRLang.fr["Remove"] = "Retirer"
ADRLang.fr["Start"] = "Démarrage"
ADRLang.fr["Stop"] = "Arrêter"
ADRLang.fr["Confirm"] = "Confirmer"
ADRLang.fr["Cancel"] = "Annuler"
ADRLang.fr["Reward"] = "Récompense"
ADRLang.fr["Module"] = "Module"
ADRLang.fr["Name"] = "Nom"
ADRLang.fr["Reward_name"] = "Nom du prix"
ADRLang.fr["New_File"] = "Nouveau dossier"
ADRLang.fr["FileStatus"] = "Fichier: "

ADRLang.fr["CreateNew"] = "Créer un Nouveau"
ADRLang.fr["StartSeason"] = "Début de la Saison"
ADRLang.fr["StopSeason"] = "Arrêt de la Saison"
ADRLang.fr["ActionNew"] = "Voulez-vous tout remettre à l'état initial ?\nVous perdrez vos paramètres actuels si vous ne\nles avez pas enregistrés."
ADRLang.fr["ActionSave"] = "Souhaitez-vous enregistrer le préréglage ?\nCela écrasera le fichier existant s'il y en a un."
ADRLang.fr["ActionRemove"] = "Êtes-vous sûr de vouloir supprimer le préréglage ?\nCela supprimera les progrès des joueurs et vous ne pourrez\nplus revenir à cette saison."
ADRLang.fr["ActionStart"] = "Voulez-vous commencer la saison avec les paramètres\nque vous avez choisis ?\nCette opération interrompt la saison en cours et\nen démarre une nouvelle."
ADRLang.fr["ActionStop"] = "Voulez-vous vraiment arrêter la saison en cours ?\nVous pouvez la reprendre plus tard, à tout moment."
/*---------------------------------------------------------------------------
German - de
---------------------------------------------------------------------------*/
ADRLang.de = ADRLang.de or {}
ADRLang.de["DAY"] = "DAY"
ADRLang.de["TIME"] = "ZEIT"
ADRLang.de["EXPIRATION_DATE"] = "VERFALLSDATUM"
ADRLang.de["UNTIL_THE_END"] = "BIS ZUM ENDE"
ADRLang.de["CURRENT_TASKS"] = "AKTUELLE AUFGABEN"
ADRLang.de["Completed"] = "Abgeschlossen"
ADRLang.de["PREMIUM"] = "PREMIUM"

ADRLang.de["SETTINGS"] = "EINSTELLUNGEN"
ADRLang.de["Themes"] = "Themen"
ADRLang.de["ThemesHint"] = "Liste der Themen, die für die visuelle Gestaltung ausgewählt werden können"
ADRLang.de["Season_Name"] = "Saison Name"
ADRLang.de["SNameHint"] = "Der Name der Saison, der im unteren linken Block angezeigt werden soll. Darf nicht eindeutig sein"
ADRLang.de["File_Name"] = "Datei Name"
ADRLang.de["SFileHint"] = "Ein eindeutiger Name, der der Saisoninformationsdatei zugewiesen wird. Wenn Sie den Namen einer bereits vorhandenen Datei eingeben, wird diese beim Speichern überschrieben. Muss in lateinischen Buchstaben ohne Leer- und Sonderzeichen angegeben werden!"
ADRLang.de["Time"] = "Time"
ADRLang.de["TimeHint"] = "Wie viele Tage wird die Saison dauern"
ADRLang.de["Task"] = "Aufgabe"
ADRLang.de["TaskHint"] = "Belohnung für die Erledigung von Aufgaben. Aufgaben werden deaktiviert, wenn es keine Belohnung gibt und die Einstellung „TasksForClaim“ in der Konfiguration deaktiviert ist"
ADRLang.de["Actions"] = "Aktionen"
ADRLang.de["ActionsHint"] = "Aktionsliste zur Verwaltung von Vorlagen und der aktuellen Saison"
ADRLang.de["New"] = "Neu"
ADRLang.de["Load"] = "Laden Sie"
ADRLang.de["Save"] = "Speichern"
ADRLang.de["Remove"] = "Entfernen"
ADRLang.de["Start"] = "Start"
ADRLang.de["Stop"] = "Stopp"
ADRLang.de["Confirm"] = "Bestätigen Sie"
ADRLang.de["Cancel"] = "Abbrechen"
ADRLang.de["Reward"] = "Belohnung"
ADRLang.de["Module"] = "Modul"
ADRLang.de["Name"] = "Name"
ADRLang.de["Reward_name"] = "Preis Name"
ADRLang.de["New_File"] = "Neue Datei"
ADRLang.de["FileStatus"] = "Datei: "

ADRLang.de["CreateNew"] = "Neu Erstellen"
ADRLang.de["StartSeason"] = "Beginn der Saison"
ADRLang.de["StopSeason"] = "Saison Beenden"
ADRLang.de["ActionNew"] = "Möchten Sie alles auf den ursprünglichen Zustand\nzurücksetzen?\nSie verlieren Ihre aktuellen Einstellungen, wenn Sie sie nicht\ngespeichert haben."
ADRLang.de["ActionSave"] = "Möchten Sie die Voreinstellung speichern?\nDadurch wird die vorhandene Datei überschrieben,\nsofern eine solche vorhanden ist."
ADRLang.de["ActionRemove"] = "Sind Sie sicher, dass Sie die Voreinstellung löschen wollen?\nDadurch wird der Fortschritt des Spielers gelöscht und\nSie können nicht mehr zu dieser Saison zurückkehren."
ADRLang.de["ActionStart"] = "Möchten Sie die Saison mit den von Ihnen gewählten\nEinstellungen beginnen?\nDamit wird die laufende Saison beendet und eine neue\nbegonnen."
ADRLang.de["ActionStop"] = "Wollen Sie die laufende Saison wirklich abbrechen?\nSie können sie jederzeit später starten."
/*---------------------------------------------------------------------------
Polish - pl
---------------------------------------------------------------------------*/
ADRLang.pl = ADRLang.pl or {}
ADRLang.pl["DAY"] = "DZIEŃ"
ADRLang.pl["TIME"] = "CZAS"
ADRLang.pl["EXPIRATION_DATE"] = "DATA WYGAŚNIĘCIA"
ADRLang.pl["UNTIL_THE_END"] = "AŻ DO KOŃCA"
ADRLang.pl["CURRENT_TASKS"] = "BIEŻĄCE ZADANIA"
ADRLang.pl["Completed"] = "Zakończono"
ADRLang.pl["PREMIUM"] = "PREMIUM"

ADRLang.pl["SETTINGS"] = "USTAWIENIA"
ADRLang.pl["Themes"] = "Themes"
ADRLang.pl["ThemesHint"] = "Lista motywów, które można wybrać dla projektu wizualnego"
ADRLang.pl["Season_Name"] = "Nazwa sezonu"
ADRLang.pl["SNameHint"] = "Nazwa sezonu wyświetlana w lewym dolnym bloku. Nie może być unikalna"
ADRLang.pl["File_Name"] = "Nazwa pliku"
ADRLang.pl["SFileHint"] = "Unikalna nazwa przypisywana do pliku z informacjami o sezonie. Jeśli wpiszesz nazwę już istniejącego pliku, zostanie ona nadpisana podczas zapisywania. Musi być podana literami alfabetu łacińskiego bez spacji i znaków specjalnych!"
ADRLang.pl["Time"] = "Czas"
ADRLang.pl["TimeHint"] = "Ile dni będzie trwał sezon"
ADRLang.pl["Task"] = "Zadanie"
ADRLang.pl["TaskHint"] = "Nagroda za wykonanie zadań. Zadania zostaną wyłączone, jeśli nie ma nagrody, a ustawienie „TasksForClaim” jest wyłączone w konfiguracji"
ADRLang.pl["Actions"] = "Działania"
ADRLang.pl["ActionsHint"] = "Lista działań związanych z zarządzaniem szablonami i bieżącym sezonem"
ADRLang.pl["New"] = "Nowość"
ADRLang.pl["Load"] = "Obciążenie"
ADRLang.pl["Save"] = "Zapisz"
ADRLang.pl["Remove"] = "Usunąć"
ADRLang.pl["Start"] = "Start"
ADRLang.pl["Stop"] = "Stop"
ADRLang.pl["Confirm"] = "Potwierdzenie"
ADRLang.pl["Cancel"] = "Anuluj"
ADRLang.pl["Reward"] = "Nagroda"
ADRLang.pl["Module"] = "Moduł"
ADRLang.pl["Name"] = "Nazwa"
ADRLang.pl["Reward_name"] = "Nazwa nagrody"
ADRLang.pl["New_File"] = "Nowy plik"
ADRLang.pl["FileStatus"] = "File: "

ADRLang.pl["CreateNew"] = "Utwórz Nowy"
ADRLang.pl["StartSeason"] = "Rozpoczęcie Sezonu"
ADRLang.pl["StopSeason"] = "Zakończenie Sezonu"
ADRLang.pl["ActionNew"] = "Czy chcesz zresetować wszystko do pierwotnego stanu?\nBieżące ustawienia zostaną utracone, jeśli nie zostały\nzapisane."
ADRLang.pl["ActionSave"] = "Czy chcesz zapisać ustawienie wstępne?\nSpowoduje to nadpisanie istniejącego pliku, jeśli taki\nistnieje."
ADRLang.pl["ActionRemove"] = "Czy na pewno chcesz usunąć ustawienie wstępne?\nSpowoduje to usunięcie postępów graczy i nie będzie\njuż można wrócić do tego sezonu."
ADRLang.pl["ActionStart"] = "Chcesz rozpocząć sezon z wybranymi ustawieniami?\nSpowoduje to zatrzymanie bieżącego sezonu i\nrozpoczęcie nowego."
ADRLang.pl["ActionStop"] = "Czy naprawdę chcesz przerwać obecny sezon?\nMożna ją uruchomić później w dowolnym momencie."
/*---------------------------------------------------------------------------
Turkish - tr
---------------------------------------------------------------------------*/
ADRLang.tr = ADRLang.tr or {}
ADRLang.tr["DAY"] = "GÜN"
ADRLang.tr["TIME"] = "ZAMAN"
ADRLang.tr["EXPIRATION_DATE"] = "SON KULLANMA TARİHİ"
ADRLang.tr["UNTIL_THE_END"] = "SONUNA KADAR"
ADRLang.tr["CURRENT_TASKS"] = "GÜNCEL GÖREVLER"
ADRLang.tr["Completed"] = "Tamamlandı"
ADRLang.tr["PREMIUM"] = "PREMIUM"

ADRLang.tr["SETTINGS"] = "AYARLAR"
ADRLang.tr["Themes"] = "Temalar"
ADRLang.tr["ThemesHint"] = "Görsel tasarım için seçilebilecek temaların listesi"
ADRLang.tr["Season_Name"] = "Sezon Adı"
ADRLang.tr["SNameHint"] = "Sol alt blokta görüntülenecek sezon adı. Benzersiz olmayabilir"
ADRLang.tr["File_Name"] = "Dosya Adı"
ADRLang.tr["SFileHint"] = "Sezon bilgileri dosyasına atanan benzersiz bir ad. Zaten var olan bir dosyanın adını yazarsanız, kaydettiğinizde bu dosyanın üzerine yazılır. Boşluk ve özel karakterler olmadan Latin harfleriyle belirtilmelidir!"
ADRLang.tr["Time"] = "Zaman"
ADRLang.tr["TimeHint"] = "Sezon kaç gün sürecek"
ADRLang.tr["Task"] = "Görev"
ADRLang.tr["TaskHint"] = "Görevleri tamamlamak için ödül. Ödül yoksa ve yapılandırmada “TasksForClaim” ayarı devre dışı bırakılmışsa görevler devre dışı bırakılacaktır"
ADRLang.tr["Actions"] = "Eylemler"
ADRLang.tr["ActionsHint"] = "Şablonları ve mevcut sezonu yönetmek için eylem listesi"
ADRLang.tr["New"] = "Yeni"
ADRLang.tr["Load"] = "Yük"
ADRLang.tr["Save"] = "Kaydet"
ADRLang.tr["Remove"] = "Kaldırmak"
ADRLang.tr["Start"] = "Başlangıç"
ADRLang.tr["Stop"] = "Dur"
ADRLang.tr["Confirm"] = "Onaylayın"
ADRLang.tr["Cancel"] = "İptal"
ADRLang.tr["Reward"] = "Ödül"
ADRLang.tr["Module"] = "Modül"
ADRLang.tr["Name"] = "İsim"
ADRLang.tr["Reward_name"] = "Ödül adı"
ADRLang.tr["New_File"] = "Yeni Dosya"
ADRLang.tr["FileStatus"] = "Dosya: "

ADRLang.tr["CreateNew"] = "Yeni Oluştur"
ADRLang.tr["StartSeason"] = "Sezon Başlangıcı"
ADRLang.tr["StopSeason"] = "Sezonu Durdur"
ADRLang.tr["ActionNew"] = "Her şeyi orijinal durumuna sıfırlamak mı istiyorsunuz?\nKaydetmediyseniz mevcut ayarlarınızı kaybedersiniz."
ADRLang.tr["ActionSave"] = "Ön ayarı kaydetmek istiyor musunuz?\nBu, eğer varsa mevcut dosyanın üzerine yazacaktır."
ADRLang.tr["ActionRemove"] = "Ön ayarı silmek istediğinizden emin misiniz?\nBu, oyuncuların ilerlemesini ortadan kaldıracak ve artık\no sezona geri dönemeyeceksiniz."
ADRLang.tr["ActionStart"] = "Sezona seçtiğiniz ayarlarla mı başlamak istiyorsunuz?\nBu, mevcut sezonu durduracak ve yeni bir sezon\nbaşlatacaktır."
ADRLang.tr["ActionStop"] = "Şu anki sezonu gerçekten durdurmak istiyor musun?\nDaha sonra istediğiniz zaman başlatabilirsiniz."
/*---------------------------------------------------------------------------
Spanish (Spain) - es-ES
---------------------------------------------------------------------------*/
ADRLang["es-ES"] = ADRLang["es-ES"] or {}
ADRLang["es-ES"]["DAY"] = "DÍA"
ADRLang["es-ES"]["TIME"] = "TIEMPO"
ADRLang["es-ES"]["EXPIRATION_DATE"] = "FECHA DE CADUCIDAD"
ADRLang["es-ES"]["UNTIL_THE_END"] = "HASTA EL FINAL"
ADRLang["es-ES"]["CURRENT_TASKS"] = "TAREAS ACTUALES"
ADRLang["es-ES"]["Completed"] = "Completado"
ADRLang["es-ES"]["PREMIUM"] = "PREMIUM"

ADRLang["es-ES"]["SETTINGS"] = "AJUSTES"
ADRLang["es-ES"]["Themes"] = "Temas"
ADRLang["es-ES"]["ThemesHint"] = "Lista de temas que pueden seleccionarse para el diseño visual"
ADRLang["es-ES"]["Season_Name"] = "Temporada"
ADRLang["es-ES"]["SNameHint"] = "Nombre de la estación que se mostrará en el bloque inferior izquierdo. Puede no ser único"
ADRLang["es-ES"]["File_Name"] = "Archivo"
ADRLang["es-ES"]["SFileHint"] = "Un nombre único que se asigna al archivo de información de la temporada. Si escribe el nombre de un fichero ya existente, lo sobrescribirá al guardarlo. Debe especificarse en letras latinas sin espacios ni caracteres especiales."
ADRLang["es-ES"]["Time"] = "Tiempo"
ADRLang["es-ES"]["TimeHint"] = "Cuántos días durará la temporada"
ADRLang["es-ES"]["Task"] = "Tarea"
ADRLang["es-ES"]["TaskHint"] = "Recompensa por completar tareas. Las tareas se desactivarán si no hay recompensa y el ajuste «TasksForClaim» está desactivado en la configuración."
ADRLang["es-ES"]["Actions"] = "Acciones"
ADRLang["es-ES"]["ActionsHint"] = "Lista de acciones para gestionar las plantillas y la temporada en curso"
ADRLang["es-ES"]["New"] = "Nuevo"
ADRLang["es-ES"]["Load"] = "Carga"
ADRLang["es-ES"]["Save"] = "Guardar"
ADRLang["es-ES"]["Remove"] = "Eliminar"
ADRLang["es-ES"]["Start"] = "Inicio"
ADRLang["es-ES"]["Stop"] = "Stop"
ADRLang["es-ES"]["Confirm"] = "Confirme"
ADRLang["es-ES"]["Cancel"] = "Cancelar"
ADRLang["es-ES"]["Reward"] = "Recompensa"
ADRLang["es-ES"]["Module"] = "Módulo"
ADRLang["es-ES"]["Name"] = "Nombre"
ADRLang["es-ES"]["Reward_name"] = "Recompensa"
ADRLang["es-ES"]["New_File"] = "Archivo nuevo"
ADRLang["es-ES"]["FileStatus"] = "Archivo: "

ADRLang["es-ES"]["CreateNew"] = "Crear Nuevo"
ADRLang["es-ES"]["StartSeason"] = "Inicio Temporada"
ADRLang["es-ES"]["StopSeason"] = "Temporada Stop"
ADRLang["es-ES"]["ActionNew"] = "¿Quieres restablecer todo a su estado original?\nPerderá su configuración actual si no la ha guardado."
ADRLang["es-ES"]["ActionSave"] = "¿Desea guardar el preajuste?\nEsto sobrescribirá el archivo existente, si existe."
ADRLang["es-ES"]["ActionRemove"] = "¿Estás seguro de que quieres borrar el preajuste?\nEsto eliminará el progreso de los jugadores y ya no\npodrás volver a esa temporada."
ADRLang["es-ES"]["ActionStart"] = "¿Quieres empezar la temporada con la configuración\nque has elegido?\nEsto detendrá la temporada actual y comenzará una\nnueva."
ADRLang["es-ES"]["ActionStop"] = "¿De verdad quieres parar la temporada actual?\nPuede iniciarlo más tarde en cualquier momento."
/*-------------------------------------------------------------------------*/

function ADRewards.GetPhrase(text)
	local ply = LocalPlayer()
	if !ply.LangADR then ply.LangADR = GetConVar("gmod_language"):GetString() end
	local lang = ADRewards.Config.ForceLanguage or ply.LangADR
	local returnedText = text
	if ADRLang[lang] and ADRLang[lang][text] then
		returnedText = ADRLang[lang][text]
	elseif ADRLang.en and ADRLang.en[text] then
		returnedText = ADRLang.en[text]
	end

	return returnedText
end