--[[
This code was generated by LAUX, a Lua transpiler
LAUX is a fork of LAU with additional changes.

More info & source code can be found at: https://gitlab.com/sleeppyy/laux
]]

AddCSLuaFile("cl_init.lua")
AddCSLuaFile("shared.lua")
include("shared.lua")

util.AddNetworkString("XeninInventory.Bank.Open")

function ENT:Initialize()
  self:SetModel(XeninInventory.Config.NPCModel)
  self:SetHullType(HULL_HUMAN)
  self:SetHullSizeNormal()
  self:SetNPCState(NPC_STATE_SCRIPT)
  self:SetSolid(SOLID_BBOX)
  self:CapabilitiesAdd(bit.bor(CAP_ANIMATEDFACE, CAP_TURN_HEAD))
  self:SetUseType(SIMPLE_USE)
  self:DropToFloor()
  self:SetMaxYawSpeed(90)
  self:DropToFloor()
end

function ENT:AcceptInput(name, activator, ply, data)
  if (name != "Use" && !IsValid(ply) && !ply:IsPlayer()) then return end

  net.Start("XeninInventory.Bank.Open")
  net.Send(ply)
end
