-- All the net messages defined here
util.AddNetworkString("pvault_msg")
util.AddNetworkString("pvault_ui")
util.AddNetworkString("pvault_ui_sell")
util.AddNetworkString("pvault_ui_makeoffer")
util.AddNetworkString("pvault_lockpick_pass")
util.AddNetworkString("pvault_lockpick_fail")
util.AddNetworkString("pvault_vault_updatebags")
util.AddNetworkString("pvault_update_ply_bags")
util.AddNetworkString("pvault_ply_leave")
util.AddNetworkString("pvault_update_id_bags")
util.AddNetworkString("pvault_update_mask")
util.AddNetworkString("pvault_config_create_entity")
util.AddNetworkString("pvault_requestdata_send")
util.AddNetworkString("pvault_requestdata_response")